# Generated by Django 3.1.7 on 2021-03-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
